#!/usr/bin/env bash

if [ ! -d dist ]; then
    npm run build
fi

cp src/public/*.html dist/public/ &&
    cp src/public/css/*.css dist/public/css/ &&
    cp src/public/js/*.js dist/public/js/ &&
    tsnd --watch ./src/public/scripts/index.ts --respawn --transpile-only --exit-child src/index.ts
